//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace E_Learning.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class Student
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Student()
        {
            this.StudentSubjects = new HashSet<StudentSubject>();
        }
    
        public string StuID { get; set; }
        [Display(Name = " Name")]
        [Required(ErrorMessage = "Student Name is needed")]
        public string StuName { get; set; }
        [Display(Name = " Age")]
        public Nullable<int> StuAge { get; set; }
        [Display(Name = " Mobile")]
        public string StuMobile { get; set; }
        [Display(Name = " Address")]
        public string StuAddress { get; set; }
        [Display(Name = " Photo")]
        public string StuPhoto { get; set; }
        public Nullable<bool> active { get; set; }
        public Nullable<int> levelID { get; set; }
    
        public virtual Class Class { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<StudentSubject> StudentSubjects { get; set; }
    }
}
