//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace E_Learning.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class StuSubTea
    {
        public int StuSubTeaID { get; set; }
        public Nullable<int> StuSubID { get; set; }
        public string TeachId { get; set; }
        public Nullable<System.DateTime> ReDate { get; set; }
    
        public virtual StudentSubject StudentSubject { get; set; }
        public virtual Teacher Teacher { get; set; }
    }
}
