//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace E_Learning.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class Teacher
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Teacher()
        {
            this.StuSubTeas = new HashSet<StuSubTea>();
            this.TeacherClasses = new HashSet<TeacherClass>();
        }
    
        public string TeachId { get; set; }
        [Display(Name = "Teacher Name")]
        public string TeachName { get; set; }
        [Display(Name = "Teacher Mobile")]
        public string TeachMobile { get; set; }
        [Display(Name = "Teacher Address")]
        public string TeachAddress { get; set; }
        [Display(Name = "Teacher Photo")]
        public string TeachPhoto { get; set; }
        public Nullable<int> SubID { get; set; }
        public Nullable<bool> active { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<StuSubTea> StuSubTeas { get; set; }
        public virtual Subject Subject { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TeacherClass> TeacherClasses { get; set; }
    }
}
