//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace E_Learning.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Thevideo
    {
        public int VideoId { get; set; }
        public string VideoPath { get; set; }
        public Nullable<System.DateTime> Date { get; set; }
        public int TeaClassID { get; set; }
        public Nullable<int> NumOfView { get; set; }
        public Nullable<bool> IsIntroVideo { get; set; }
        public string Title { get; set; }
    
        public virtual TeacherClass TeacherClass { get; set; }
    }
}
